### ISSUE TITLE
safecopy-0.8.3 test suite failures on Linux

### ISSUE THREAD

**Issue by peti** [acid-state/safecopy#17]
I cannot compile the test suite on Linux with GHC 7.8.4. A complete build log is available at http://hydra.cryp.to/build/357301/nixlog/1/raw.

**Comment by dredozubov** [comment]
This has been fixed by https://github.com/acid-state/safecopy/commit/a2fc0746ce49ba7230a55668835d2d1bffa86897
and can be closed.

**Comment by peti** [comment]
Thank you!
