### ISSUE TITLE
safecopy-0.8.3 broken with GHC 7.10

### ISSUE THREAD

**Issue by hvr** [acid-state/safecopy#19]
The following snippet works fine with GHC 7.8.4 and `safecopy-0.8.3`

```hs
{-# LANGUAGE TemplateHaskell #-}

import Data.SafeCopy

newtype Log a = Exp { ln :: a } deriving (Eq,Ord)

deriveSafeCopy 1 'base ''Log
```

but with GHC 7.10 it fails to compile with

```
test.hs:7:1:
    Expecting one more argument to ‘Log’
    The first argument of ‘SafeCopy’ should have kind ‘*’, but ‘Log’ has kind ‘* -> *’
    In the instance declaration for ‘SafeCopy Log’
```

**Comment by en-em** [comment]
I too wonder what's going on here.

**Comment by Qinka** [comment]
Me too. I build hackage-server , when this happened.

**Comment by Qinka** [comment]
I guess that we were missing something just like {-# LANGUAGE XX #-}. But what XX is ?

**Comment by slpopejoy** [comment]
I did -ddump-splices on this as it's breaking log-domain, which I presume is where the example above comes from. Replacing the TH code with the following emitted code has the same problem:

```haskell
instance SafeCopy Log where
      putCopy (Exp arg_afqB)
        = contain
            (do { safePut_a_afqC <- getSafePut;
                  safePut_a_afqC arg_afqB;
                  return () })
      getCopy
        = contain
            (label
               "Numeric.Log.Log:"
               (do { safeGet_a_afqD <- getSafeGet;
                     ((return Exp) <*> safeGet_a_afqD) }))
      version = 1
      kind = base
      errorTypeName _ = "Numeric.Log.Log"
```

```
src/Numeric/Log.hs:77:19-21: Expecting one more argument to ‘Log’ …
    The first argument of ‘SafeCopy’ should have kind ‘*’,
      but ‘Log’ has kind ‘* -> *’
    In the instance declaration for ‘SafeCopy Log’
Compilation failed.
```

To fix the code, change the instance decl to `instance SafeCopy a => SafeCopy (Log a) where`. This compiles.

I think the TH code would need to be changed to fix this, I'll take a look.

**Comment by stepcut** [comment]
The snippet works for me with GHC 7.10.3 and safecopy 0.9.0.1. I'm guessing this patch fixed it:

https://github.com/acid-state/safecopy/commit/899152cf334407177583a6ff60815aee266f65f5
