### ISSUE TITLE
Release safecopy-0.8.6 that builds with vector-0.11

### ISSUE THREAD

**Issue by DanBurton** [acid-state/safecopy#33]
I see that the github repo already loosened the upper bound on vector; I'm just requesting a release to hackage.

**Comment by snoyberg** [comment]
Bumping, this is currently blocking Stackage from updating to vector 0.11. Pretty soon, we'll need to drop safecopy from Stackage.

**Comment by Lemmih** [comment]
Done, 0.8.6 is on hackage.

**Comment by snoyberg** [comment]
Thanks!

On Mon, Oct 19, 2015 at 7:33 AM, David Himmelstrup <notifications@github.com
