### ISSUE TITLE
Loose time package constraint

### ISSUE THREAD

**Issue by juanpaucar** [acid-state/safecopy#43]
Should I make a pull request or is it enough to post it here.

time is currently
`time < 1.6,` but is safe to change it to `time < 1.7,` since its [changelog](time < 1.6,) doesn't mention something that could harm the library.

PS: I would also like to mention that the changes in #37 are merged here but not yet uploaded to hackage and it's the last step to have it working with GHC 8

**Comment by stepcut** [comment]
Fixed in safecopy-0.9.1
