### ISSUE TITLE
template-haskell constraint for ghc-8.4.1

### ISSUE THREAD

**Issue by claudeha** [acid-state/safecopy#62]
`ghc-8.4.1` comes with `template-haskell-2.13.0.0` but `safecopy-0.9.4` depends on `template-haskell < 2.13`.  I installed successfully with `cabal install --allow-newer=template-haskell` but I haven't run the test-suite to be sure all is ok.

**Comment by ddssff** [comment]
I don't see any harm in relaxing this constraint - it can't break anything that isn't already broken.  OTOH, running the test suite would be good.

**Comment by ddssff** [comment]
Uploaded: Version 0.9.4.1
