### ISSUE TITLE
incompatible with GHC 8.6

### ISSUE THREAD

**Issue by clinty** [acid-state/safecopy#68]
Upper bound on template-haskell is problematic

**Comment by clinty** [comment]
Appears that all that is necessary is to fix the upper bounds on template-haskell and containers.

**Comment by RyanGlScott** [comment]
#69 would fix this.

**Comment by clinty** [comment]
still, containers 0.6 is bundled with ghc 8.6.1

**Comment by RyanGlScott** [comment]
Oops! I overlooked `containers`, since I somehow managed to install an older version when I tried building `safecopy` locally. I've amended #69 to address this.
